version: '2'
services:
  mariadb:
    restart: always
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_phpbb
      - MARIADB_DATABASE=bitnami_phpbb
    volumes:
      - './mariadb_data:/bitnami/mariadb'
  phpbb:
    restart: always
    image: docker.io/bitnami/phpbb:${SOFTWARE_VERSION_TAG}
    ports:
      - '172.17.0.1:2380:8080'
      # - '443:8443'
    environment:
      - PHPBB_DATABASE_HOST=mariadb
      - PHPBB_DATABASE_PORT_NUMBER=3306
      - PHPBB_DATABASE_USER=bn_phpbb
      - PHPBB_DATABASE_NAME=bitnami_phpbb
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - PHPBB_USERNAME=root
      - PHPBB_PASSWORD=${ADMIN_PASSWORD}
      - PHPBB_EMAIL=${ADMIN_EMAIL}
    volumes:
      - './phpbb_data:/bitnami/phpbb'
    depends_on:
      - mariadb
